### ISSUE TITLE
รับสินค้าจากการซื้อ เพิ่มตัว mark เพื่อจะปิดรับ auto

### ISSUE THREAD

**Issue by Natkun** [mophos/mmis-inventory-frontend#112]
รองรับกรณีที่สินค้าตอนมาส่งราคาถูกกว่าใบสั่งซื้อ 
![image](https://user-images.githubusercontent.com/20655314/38194127-d117b682-369f-11e8-930e-b2b4c936df9a.png)

**Comment by siteslave** [comment]
![screen shot 2561-05-09 at 17 00 30](https://user-images.githubusercontent.com/526890/39809290-9245aeb8-53ab-11e8-97db-1e53a61229e2.png)
